os: 
  - Visual Studio 2015
  - Visual Studio 2013

platform:
  - Win32
  - Win64

before_build:
  - ps: Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-Webrequest "https://raw.githubusercontent.com/xmake-io/xmake/dev/scripts/get.ps1" -UseBasicParsing).Content)) -ArgumentList "dev"
  - cmd: xmake --version
  - cmd: git clone https://github.com/xmake-io/xmake.git -b repo
  - cmd: cd xmake
  - cmd: xmake -P core 
  - cmd: set XMAKE_PROGRAM_DIR=%cd%\xmake
  - ps: Copy-Item -Force core\build\xmake.exe $HOME\xmake
  - cmd: xmake --version

build_script:
  - cmd: xmake l scripts/test.lua

