sudo: false
language: C
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

install:
  - git clone --branch=dev https://github.com/xmake-io/xmake.git tboox/xmake --depth 1
  - cd ./tboox/xmake
  - ./scripts/get.sh __local__
  - cd -
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip -O /tmp/android-ndk-r19c-linux-x86_64.zip
      unzip /tmp/android-ndk-r19c-linux-x86_64.zip;
    fi

script:
  - travis_wait 60 xmake l ./scripts/test.lua -D
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      travis_wait 60 xmake l ./scripts/test.lua -D -p iphoneos;
    else
      travis_wait 60 xmake l ./scripts/test.lua -D -p android --ndk=/tmp/android-ndk-r19c;
    fi
