sudo: false
language: C
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

install:
  - git clone --branch=dev https://github.com/xmake-io/xmake.git tboox/xmake --depth 1
  - cd ./tboox/xmake
  - ./scripts/get.sh __local__
  - cd -

script:
  - travis_wait 60 xmake l ./scripts/test.lua -D

