sudo: false
language: C
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

install:
  - git clone --branch=dev https://github.com/xmake-io/xmake.git tboox/xmake --depth 1
  - cd ./tboox/xmake
  - ./scripts/get.sh __local__
  - cd -
  - if [ "$TRAVIS_OS_NAME" = "osc" ]; then
      brew install mingw-w64;
    else
      wget -q https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip;
      unzip -q -o ./android-ndk-r19c-linux-x86_64.zip;
    fi

script:
  - travis_wait 60 xmake l ./scripts/test.lua -D
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      travis_wait 60 xmake l ./scripts/test.lua -D -p iphoneos;
      travis_wait 60 xmake l ./scripts/test.lua -D -p mingw;
    else
      travis_wait 60 xmake l ./scripts/test.lua -v -D -p android --ndk=`pwd`/android-ndk-r19c;
    fi
